fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "3.2.0"
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    zypprepo: https://github.com/deadpoint/puppet-zypprepo.git
  symlinks:
    logstash: "#{source_dir}"
