fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "3.2.0"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    zypprepo: "git://github.com/deadpoint/puppet-zypprepo.git"
  symlinks:
    logstash: "#{source_dir}"
