language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
script:
  - "rake lint"
  - "rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0"
      gemfile: .gemfile
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
      gemfile: .gemfile
    - rvm: ruby-head
      env: PUPPET_VERSION="~> 2.7.0"
      gemfile: .gemfile
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
      gemfile: .gemfile
gemfile: .gemfile
notifications:
  email:
    - richard@ispavailability.com
